### ISSUE TITLE
Potencijalna unapredjenja

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp2019/ConstPlusPlus#1]
- Mozda dodati poruku dok se formira raspored, cisto da ne bude prazan prozor 
- Mozda staviti citavi GUI u scroll-able komponentu (recimo tableti ili telefoni ne mogu da prikazu ceo ekran)
- U rasporedu za `JAG 3&4` stoji `JAG 3&amp;4` :)

**Comment by aleksandar-stefanovic** [comment]
> * Mozda dodati poruku dok se formira raspored, cisto da ne bude prazan prozor

Dodat ProgressIndicator koji se "vrti" dok se ne prikaže nešto.
> * Mozda staviti citavi GUI u scroll-able komponentu (recimo tableti ili telefoni ne mogu da prikazu ceo ekran)

Ova aplikacija je namenjena za PC okruženja (nije namenjena za mobilne uređaje, iako teoretski JavaFX može da se prikaže na telefonu). Za mobilnu aplikaciju bi se koristio sasvim drugi sistem za grafički interfejs.

> * U rasporedu za `JAG 3&4` stoji `JAG 3&amp;4` :)

Ispravljeno.
